### ISSUE TITLE
Extract per-gene-per-mutation rates from partis

### ISSUE THREAD

**Issue by BrandenOlson** [matsengrp/sumrep#1]
During an annotation, partis [creates files](https://github.com/psathyrella/partis/blob/master/manual.md#cache-parameters) that detail per-allele-per-position mutation rates for V/D/J alleles inferred to construct the naive sequence of a given mature sequence. These rates are one way to summarize a repertoire, and we aim to 
use these summaries to compare repertoires.

I will create a script that converts a given yaml file to a format usable within sumrep, i.e. parse the data into data.table objects, perhaps using the [yaml package](https://cran.r-project.org/web/packages/yaml/index.html). I will then write another script (or R function) that iterates through each yaml file and combines them into one data.table. If it makes sense, I will append this data.table to the one currently returned in annotateSequences, or just return a list of the two separate data.tables. Finally, I will write a function to compare per-gene and per-gene-per-position mutation rates of two different repertoires.

**Comment by matsen** [comment]
@scharch stated that this is quite high dimensional, and @mikessh commented that this is going to be fairly unstable because it can be thrown off by sequencing error. I maintain that it's going to be worthwhile for frequently observed alleles in the repertoire. Everything else imposes some sort of modeling assumption about what determines these rates.

Clearly one can't compare two arbitrary repertoires in this way. However, it's quite useful in comparing the difference between, say, an original repertoire and a simulated repertoire that is meant to recapitulate properties of the original repertoire. E.g. from the [IGoR preprint](http://arxiv.org/abs/1705.08246):

![screenshot 2017-08-03 at 2 50 31 pm](https://user-images.githubusercontent.com/112708/28945387-22ff5b02-785b-11e7-96e6-faa7adb9e7ea.png)
