### ISSUE TITLE
-locus: invalid choice: 'ig'

### ISSUE THREAD

**Issue by Pezhvuk** [matsengrp/sumrep#24]
Hi Branden,

 I'm not sure if I have done something wrong/silly, but despite sumrep not complaining about passing 'ig' to the `locus` parameter of `getPartisAnnotations`, the following error is reported back by `partis` (only available due to changes as discussed in #23): 
`partis partition: error: argument --locus: invalid choice: 'ig' (choose from 'tra', 'trb', 'trd', 'trg', 'igl', 'igk', 'igh')`

Here is the code I used:
```
library(devtools)
library(ape)
devtools::load_all("/d/as2/u/mp002/sumrep_14-03-2019")

seq_path = "/d/as2/u/mp002/sumrep_project/tests/test_fasta/S-FV_+14d.fasta"

partis_output <- getPartisAnnotations(seq_path, locus="ig")
```

Changing the 'ig' to 'igh', however, fixed the issue. I know that sumrep should not have a problem with this and handle 'ig' as an input, so, wondered what the problem might be?

Cheers,
Peji.

**Comment by BrandenOlson** [comment]
Since partis requires an explicit locus, sumrep should also require an explicit locus. E.g. if sumrep allows `ig`, partis doesn't know whether it's `igh`, `igk`, or `igl`, and I'm hesitant to assume a default here. Thus, I will fix this so that `getPartisAnnotations` throws an error if `locus` is not one of `tra`, `trb`, `trd`, `trg`, `igl`, `igk`, `igh` as required by partis.

**Comment by Pezhvuk** [comment]
Sounds reasonable.
