### ISSUE TITLE
Distances between mutations on BCRs

### ISSUE THREAD

**Issue by matsen** [matsengrp/sumrep#4]
The IGoR paper does a nice analysis of distances between mutations. By this, we mean the genomic distance between mutated bases. E.g. if `M` means mutated and `g` means germline, then a sequence like 

```
ggggggMgggMggggg
```

would have a distance between mutations of 3. 

They make a transform of the distribution of these distances to compare the distance between mutations to what one would expect under an independence model. I don't think that we need to do so here, and just propose looking at the distributions of distances itself.

**Comment by BrandenOlson** [comment]
There are two special cases to consider:
* Cases where mature == naive, so that there are no mutations
* Cases where there is only one mutation from naive to mature.

Perhaps the most sensible thing to do (and what I'm implementing now) is to discard these two cases in the comparison, so that we restrict to the conditional distribution of distances between mutations given #{mutations in a sequence} >= 2.
