### ISSUE TITLE
Proportion of out-of-frame sequences

### ISSUE THREAD

**Issue by BrandenOlson** [matsengrp/sumrep#8]
A newly suggested summary statistic is the proportion of out-of-frame sequences in a dataset. This can be easily handled using `partis` annotations, since `in_frame` is already a returned attribute in the csv output. Thus, I was thinking of implementing a simple function like the following:
```
getInFramePercentage <- function(dat) {
    in_frame_percentage <- 100*(dat$in_frame %>% mean)
    return( in_frame_percentage )
}
```
The divergence function can simply be a scalar absolute difference.

**Comment by matsen** [comment]
Excellent!

**Comment by javh** [comment]
As far as AIRR, IMGT, IgBLAST and Change-O are concerned, these are all the same. Some discussion on it here:
https://github.com/airr-community/airr-standards/issues/75

Can't speak to partis.

**Comment by BrandenOlson** [comment]
Wonderful, @javh -- thanks for the input!

@psathyrella, does `partis`'s `vj_in_frame` fit in with the above as well? Any subtleties we should be wary of?

**Comment by scharch** [comment]
It certainly sounds to me like the partis definition is a bit different: as
I understand it, a sequence with compensating indels, say a 1 nt deletion
in CDR1 and a 37 nt CDR3 would be considered "in frame" by partis, but not
by the other definitions.

**Comment by psathyrella** [comment]
@BrandenOlson @scharch 

From reading the three descriptions, I think (I'm not sure) that they'd in practice be the same in the vast majority of cases. So what I *do* is super simple: `v_cpos % 3 == 0 and j_cpos % 3 == 0` (zero indexed). My convoluted language ^ was just trying to be more clear, but I remember being unhappy with it, and the other descriptions sound better to me.

I could be misunderstanding, but a 1nt deletion before the cysteine would knock the cysteine out of frame, so partis would mark it as out of frame. Maybe my description doesn't make it clear enough that I'm requiring both cyst *and* tryp/phen to be in frame?

But if the compensating indels were both *before* the cyst, then yes, partis would mark it as in frame. I would probably argue that this is what we want, since otherwise I'd have to start deciding exactly where cdr1 and cdr2 vs V fwks are, which I want to avoid, since there doesn't seem to be a uniformly accepted standard for where these are (there's a b-t.cr thread I'm thinking of here).

**Comment by scharch** [comment]
@psathyrella -ok that makes sense. I read the definition as being in-frame
*with each other*, which would only require the Trp, but the Cys. In
hindsight, I think the confusion there is all on me, but thanks for
clarifying.

**Comment by BrandenOlson** [comment]
Great, thanks everyone! I'll consider these definitions practically equivalent for `sumrep` and compliant with the AIRR standard.
